In [2]:
import pandas as pd

from imports import *

In [3]:
from config import dir_config

raw_dir = Path(dir_config.data.raw)
processed_dir = Path(dir_config.data.processed)

filtered_data = pd.read_csv(Path(processed_dir, "processed_all_data_accu_60_filtered.csv"), index_col=None)
processed_metadata = pd.read_csv(Path(processed_dir, "processed_metadata_all_data_accu_60.csv"), index_col=None)

In [8]:
filtered_data.head()

,subject_id,group,medication,prior,prior_direction,prior_color,color,coherence,target,is_valid,outcome,choice,reaction_time,session_filename,signed_coherence,session_id
0,HC6,hc,NaN,gl,left,green,1,35.0,1,True,1.0,1,1131.517634,HC6_healthy_gl.mat,35.0,HC6
1,HC6,hc,NaN,gl,left,green,0,35.0,1,True,1.0,1,788.931217,HC6_healthy_gl.mat,35.0,HC6
2,HC6,hc,NaN,gl,left,green,1,13.0,1,True,0.0,0,1192.128380,HC6_healthy_gl.mat,13.0,HC6
3,HC6,hc,NaN,gl,left,green,1,0.0,0,True,0.0,1,1589.536018,HC6_healthy_gl.mat,-0.0,HC6
4,HC6,hc,NaN,gl,left,green,1,100.0,0,True,1.0,0,781.757934,HC6_healthy_gl.mat,-100.0,HC6

In [9]:
behavior_df = pd.DataFrame()

# now grab the relevant columns from the filtered data and put them in the behavior_df
behavior_df["session_id"] = filtered_data["session_id"]
behavior_df["prior_direction"] = filtered_data["prior_direction"]
behavior_df["signed_coherence"] = filtered_data["signed_coherence"]
behavior_df["color"] = filtered_data["color"]
behavior_df["target"] = filtered_data["target"]
behavior_df["choice"] = filtered_data["choice"]
behavior_df["outcome"] = filtered_data["outcome"]
behavior_df["rt"] = filtered_data["reaction_time"]


behavior_df = behavior_df.dropna().reset_index(drop=True)
if behavior_df["signed_coherence"].max() > 1:
    print("Warning: signed_coherence has values greater than 1, dividing by 100!")
    behavior_df["signed_coherence"] /= 100  # convert to proportion for plotting
if behavior_df["rt"].max() > 10:
    print("Warning: rt has values greater than 10 seconds, dividing by 1000!")
    behavior_df["rt"] /= 1000  # convert to seconds for plotting

# sanity check
print(behavior_df["signed_coherence"].value_counts().sort_index())
print(behavior_df["target"].value_counts())
print(behavior_df["choice"].value_counts())

Warning: signed_coherence has values greater than 1, dividing by 100!
Warning: rt has values greater than 10 seconds, dividing by 1000!
signed_coherence
-1.00     6212
-0.35     6095
-0.13     6004
-0.00    15548
 0.13     9601
 0.35     9727
 1.00     9910
Name: count, dtype: int64
target
1    38810
0    24287
Name: count, dtype: int64
choice
1    35584
0    27513
Name: count, dtype: int64

In [15]:
behavior_df.head()

,session_id,prior_direction,signed_coherence,color,target,choice,outcome,rt
0,HC6,left,0.35,1,1,1,1.0,1.131518
1,HC6,left,0.35,0,1,1,1.0,0.788931
2,HC6,left,0.13,1,1,0,0.0,1.192128
3,HC6,left,-0.00,1,0,1,0.0,1.589536
4,HC6,left,-1.00,1,0,0,1.0,0.781758

In [10]:
behavior_df.to_csv(Path(processed_dir, "ddm", "behavior_data.csv"), index=False)